### PR TITLE
Rewrite README. 

### PR DESCRIPTION
**Pull request by rosiel**
**JIRA Ticket**: none, it's documentation 😀
**Sister PR**: #47

# What does this Pull Request do?

Rewrites the README + admin form help text to be user-friendlier.

# What's new?

* Adds a screenshot to the introduction to show what a "solr facet page" is.
* Highlights in several places that "solr facet pages are at /browse/your-path". 
* Explains the options in the configuration form individually, and explains how to select the right kind of solr fields. 
* Wording changed for clarity, fixed a couple typos.
* Removed "Leave empty to show all fields" because an empty value won't pass validation.

# Known issues

* The final feature on the form, Lucene Syntax Escaping and its associated regex, remains undocumented. I don't understand enough of the how or why to document it, but it also exists in Solr Search. In the spirit of iterative improvement, I'll make a separate ticket/task for documenting that feature. 
* Testing revealed some weirdness with "Maximum facet values" (formerly, Maximum searchable facet values). 
  * On the individual alphabet queries you may find as many as twice this limit. That's because two queries are done, e.g. myfield:A* and myfield:a* and the limit applies separately to each query. If your limit is 500 you might get up to 1000 in the "A's". I didn't document this weirdness, and we may want to fix it. 
  * The values that got dropped (when this maximum values limit took effect) were not "predictable" - they were neither the least popular values nor the values at the end of the alphabet. I documented this. If we would like to change how it works, I also made a ticket. 

# How should this be tested?

Find a person who's never used Solr Facet Pages before, and ask them to set one up.

# Additional Notes:

* Does this change require documentation to be updated? YES if this is accepted I will change the wiki to reflect it, too.
* Does this change add any new dependencies? no
* Does this change require any other modifications to be made to the repository (ie. Regeneration activity, etc.)? no
* Could this change impact execution of existing code? hell no (unless by documenting we realize that maybe the code isn't doing what's intended and so decide to change it 🙃)

# Interested parties
@Islandora/7-x-1-x-committers and Documentation IG @DonRichards and Gabriela Mircea (anyone know her Github tag?)

### CODE REVIEW

**Comment by rosiel** [comment]
The readme's visible on github at https://github.com/rosiel/islandora_solr_facet_pages/tree/7.x-documentation.

Ping @nhart (maintainer) or anyone else - mind taking a look? Thanks!

**Comment by rosiel** [comment]
Hey @bencomp (documenter for facet pages) just fyi - this pull is sitting here and could be a starting place for documenting Solr Facet Pages, if you want to use it.

**Review by bondjimbond — APPROVED** [review]
@rosiel Having never set up a Solr Facet Page before, the README does the trick. Thanks!

**Comment by bondjimbond** [comment]
@rosiel @DiegoPino Does this have to wait until after the release, then? Or should there be an equivalent pull on 7.x-1.11?

**Comment by DiegoPino** [comment]
Yes, we need one for that. Readme files (instructions) if applicable to the release code need to go also into the release  branch (that is why we have documenters and testers).

**Comment by bondjimbond** [comment]
Thanks! So once @rosiel has an equivalent pull in the release branch, I'll merge them both (in 23 hours of course).

**Pull request merged**
