### PR TITLE
ISLANDORA-1698 - update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by aulorbe**
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1698

# What does this Pull Request do?

Adds Islandora Community of Conduct link & copy to CONTRIBUTING.md within the Islandora SOLR Facet Pages repo (https://github.com/Islandora/islandora_solr_facet_pages).

# Interested parties
@manez

### CODE REVIEW

**Comment by DiegoPino** [comment]
@aulorbe thanks! So many good pull requests

**Comment by DiegoPino** [comment]
@aulorbe also, if you name your branches instead of `patch-1` this way: `7.x-ISLANDORA-1698`  (which is the branch = 7.x and the JIRA Ticket number = ISLANDORA-1698) JIRA will associate all this pull requests directly to the ticket. Not imposed of course, and no need to make any changes to existing ones, but sometimes its a good idea when a change affects many repositories so keeping track if any pull request was missing becomes an easier task. Thanks 😄

**Comment by DiegoPino** [comment]
@ruebot sorry. Pinched over you because git was suggesting your name. Please ignore

**Review by DiegoPino — APPROVED** [review]

**Comment by aulorbe** [comment]
@DiegoPino, just saw your comment. Thanks, I will try that with the next few!

**Comment by manez** [comment]
@DiegoPino the way @aulorbe has been doing them with the JIRA ticket number as the first part of the commit message also triggers JIRA to pick it up. It's been catching them: https://jira.duraspace.org/browse/ISLANDORA-1698

**Comment by DiegoPino** [comment]
@manez cool. thanks for correcting me.

**Pull request merged**
