### PR TITLE
Update Islandora Solr link, change minor wording

### PR DESCRIPTION
**Pull request by bencomp**
This is part of the effort to update the documentation for the 7.x-1.11 release.

I noticed that the 7.x and 7.x-1.11 trees have diverged, but is it my responsibility to create a new branch, rebase it on the 7.x-1.11 branch and use that for this PR?

**JIRA Ticket**: n/a

# What does this Pull Request do?

This PR updates the link text for the Islandora Solr module and offers a typographic and a wording change.

# What's new?

* a screenshot is now in the repository under `docs/`
* the Islandora Solr module was listed as Islandora Solr Search
* folder layout example for custom theme is now a full sentence

# How should this be tested?

Check that this is more understandible.

# Additional Notes:
none

# Interested parties
@nhart

### CODE REVIEW

**Comment by DiegoPino** [comment]
@bencomp this one has conflicts. Your are bringing some 7.x pulls to this one. What i would do (simpler workflow):
A) ~~make the 7.x pull first (simpler), maybe you have it?~~ UPDATE, SORRY, here it is! https://github.com/Islandora/islandora_solr_facet_pages/pull/48/files 
B) Close this pull and get a fresh copy of then 7.x-1.11 branch, create a new branch based on that one for your to-be pull request. Apply the changes (REAME.md) manually by copy and pasting the whole content on the README file from 7.x into that one. Make the pull request.

Does that make sense? @rosiel for sure will have a more complete workflow with a lot of better steps, but in doubt, I feel you can give my simplistic one a try. Let me know you need help

**Comment by DiegoPino** [comment]
@bencomp any chance you can address this one before Friday, release time? If not let me know and I open a pull and we deal with it internally. Thanks! @rosiel ping just so you know we will have to deal with this one which is the release equivalent of https://github.com/Islandora/islandora_solr_facet_pages/pull/48

**Comment by rosiel** [comment]
It's been 24h - I'm going to resolve the conflicts here in the web editor. Sorry folks!

**Comment by rosiel** [comment]
Hmm... that did not do what I expected. I'm really really sorry. 
* I hadn't noticed the docs folder came in with this PR, so I mistakenly undid the change in pointing to the png in the docs folder. 
* I didn't realize the first three commits were already (essentially) in the 7.x-1.11 branch. 

Having used my super-git-powers to mess this up, I'm going to use my super-git-powers to undo my mess, which will leave us with a PR that's not clean in terms of git history but will cause the desired changes to the code.

**Comment by bencomp** [comment]
Sorry for not responding sooner. If still necessary, I will have a look. I think it is very suboptimal to have multiple branches with the exact same content and keeping those branches in parallel. At some point there should be a merge of 7.x and 7.x-1.11, but it doesn't have to be this pull request that updates the docs and merges the branches.

**Comment by DiegoPino** [comment]
@bencomp reason we keep diverging branches is CODE FREEZE. Basically, non-urgent, improvements, new functionality, etc can still be developed on 7.x, while the release branch, which will become stalled and untouchable, will only accept bug fixes. It is the only way we found to actually be able to have a release, or testing each new commit that happens would make our releases unmanageable and untestable, probably reducing the quality of the code people expect from a formally versioned processed. But we are open to rethinking processes, of course, the only reason really why open is so appealing to me (re-thinking, re-structuring, burning to the ground and letting new ideas grow)

**Comment by DiegoPino** [comment]
@rosiel i feel that clean git history is desired, but we can discuss this during the day. Skype?

**Comment by DiegoPino** [comment]
Ok, we discussed this and good arguments were given to move forward as is, git history on a frozen branch is less complicated than in 7.x. I will merge. Thanks @bencomp and @rosiel for dealing with this on time. ❤️

**Pull request merged**
