### PR TITLE
7.x update readme 1955

### PR DESCRIPTION
**Pull request by CanOfBees**
**JIRA Ticket**: https://jira.duraspace.org/browse/ISLANDORA-1955

# What does this Pull Request do?
This PR updates the README to reflect a potential problem with using Facet Search Form.

# What's new?
* Updated the screenshot to mirror the Confluence documentation.
* Added a note below the screenshot to reflect outcomes from using the Facet Search Form.

# How should this be tested?
There are only changes to the README's markdown, so a reading-only review might be sufficient. 

# Additional Notes:
The Confluence documentation should be updated to reflect this change - at least until the search behavior can be addresssed.

# Interested parties
@Islandora/7-x-1-x-committers

### CODE REVIEW

**Comment by manez** [comment]
@CanOfBees could you change this to be a new "Notes" section, as seen in [videojs](https://github.com/Islandora/islandora_videojs)? This has been the pattern we use when adding extra notes on configuration, and it leaves room for more to be added later. Thanks!

**Comment by CanOfBees** [comment]
@manez absolutely yes -- I'll get this fixed shortly!

**Comment by CanOfBees** [comment]
@manez Let me know if there are any other changes needed. Thank you!

**Comment by manez** [comment]
@CanOfBees tiny thing: Can you make it "Notes" instead of "Note"? Just to match up with the other readmes.

**Comment by DiegoPino** [comment]
@CanOfBees this will sound super silly. But just if possible (and feel free to just tell me not). Could the screenshot not have the Drupal update warnings? Reason is, non Drupal aware folks could eventually be fearing/not understanding the context of that message there or even expecting it in their own installations/ when it is really a Drupal thing and not a facets. Please stop me if i'm too picky.

**Comment by manez** [comment]
I'll second @DiegoPino 's point (and nice catch!). I'm so used to those warnings that I didn't even notice, but it could be distracting to a newcomer 😄

**Comment by CanOfBees** [comment]
@manez that's just me being a bad typist :). 

@DiegoPino absolutely! I pulled the screenshot from Confluence -- I'll update both. Thanks for catching that.

**Comment by DiegoPino** [comment]
@CanOfBees thanks to you for being so diligent. cool

**Comment by CanOfBees** [comment]
@DiegoPino @manez should the new screenshot be exactly like the original (minus the Drupal warnings); e.g. should it use `dc.subject_s`, etc.?

**Review by manez — APPROVED** [review]

**Comment by manez** [comment]
@CanOfBees @DiegoPino looks good here. Just waiting on Travis and I'll merge this and #41

**Pull request merged**
