### PR TITLE
Use IslandoraSolrQueryProcessor to ensure query alter hooks are called.

### PR DESCRIPTION
**Pull request by whikloj**
Adds autocomplete to the admin field.
Addresses [ISLANDORA-1388](https://jira.duraspace.org/browse/ISLANDORA-1388)

### CODE REVIEW

**Comment by whikloj** [comment]
I have added a `'hl' => 'false'` to the params_array so that highlighting will be turned off for these queries.

Essentially it takes the $facet_params like this:

```
...
(Array, 7 elements)
facet (String, 4 characters ) true
facet.field (String, 21 characters ) mods_subject_topic_ms
facet.sort (String, 5 characters ) index
facet.mincount (Integer) 1
facet.limit (String, 6 characters ) 100000
qt (String, 8 characters ) standard
hl (String, 5 characters ) false
```

Passes it to the IslandoraSolrQueryProcessor which turns them into this.

```
... (Array, 10 elements)
facet (String, 4 characters ) true
facet.mincount (String, 1 characters ) 2
facet.limit (String, 2 characters ) 20
facet.field (Array, 1 element)
  0 (String, 43 characters ) mods_subject_hierarchicalGeographic_city_ms
hl (String, 4 characters ) true
hl.fl (String, 23 characters ) mods_titleInfo_title_ms
hl.fragsize (Integer) 400
hl.simple.pre (String, 39 characters ) <span class="islandora-solr-highlight">
hl.simple.post (String, 7 characters ) </span>
fq (Array, 2 elements)
  0 (String, 16 characters ) PID:islandora\:*
  1 (String, 41 characters ) -RELS_EXT_isConstituentOf_uri_mt:[* TO *]
  2 (String, 276 characters ) RELS_EXT_isViewableByUser_literal_ms:"admin" OR...
```

Then we overwrite the changed facet elements to get rid of the default Solr search stuff (via the array_replace_recursive() ) and end up with:

```
... (Array, 12 elements)
facet (String, 4 characters ) true
facet.mincount (Integer) 1
facet.limit (String, 6 characters ) 100000
facet.field (String, 21 characters ) mods_subject_topic_ms
hl (String, 5 characters ) false
hl.fl (String, 23 characters ) mods_titleInfo_title_ms
hl.fragsize (Integer) 400
hl.simple.pre (String, 39 characters ) <span class="islandora-solr-highlight">
hl.simple.post (String, 7 characters ) </span>
fq (Array, 2 elements)
  0 (String, 16 characters ) PID:islandora\:*
  1 (String, 41 characters ) -RELS_EXT_isConstituentOf_uri_mt:[* TO *]
  2 (String, 276 characters ) RELS_EXT_isViewableByUser_literal_ms:"admin" OR...
facet.sort (String, 5 characters ) index
qt (String, 8 characters ) standard
```

So it will not generate an extra Solr facets, nor will it call for highlighting. The important part is really the fq array, this contains the XACML restrictions and the namespace limiting.

**Comment by DiegoPino** [comment]
@whikloj, i like this version a lot better, less Solr processing and faster loading. :+1: and thanks a lot.

**Comment by whikloj** [comment]
Now also addresses [ISLANDORA-1468](https://jira.duraspace.org/browse/ISLANDORA-1468)

**Comment by whikloj** [comment]
How is this @willtp87?

**Comment by willtp87** [comment]
The API mismatch looks to be addressed.

**Pull request merged**
