### PR TITLE
Trimming search terms in islandora_solr_facet_pages

### PR DESCRIPTION
**Pull request by nmader**
# Jira Ticket: https://jira.duraspace.org/browse/ISLANDORA-1996

# What does this Pull Request do?

It was discovered during testing that when conducting a solr_facet_pages search that when the user typed a space it would create an error. 

# What's new?

The trim function is used on the search term in islandora_solr_facet_pages_search_form_submit(). 

# How should this be tested?

Create a facet search page and search for a "space" and submit the form. 

# Interested parties
Tag (@ mention) interested parties or, if unsure, @Islandora/7-x-1-x-committers

### CODE REVIEW

**Review by willtp87 — APPROVED** [review]
Forgot the ticket @nmader.

**Comment by DiegoPino** [comment]
@nmader is this trimming consistent in all search interfaces? Also, trim() is not only about leading spaces, is all spaces, before and after [and many other characters](http://php.net/manual/en/function.trim.php). I would ask you please to update the title of this pull.

I remember having this discussion about cleaning users input somewhere in islandora and consistency all over the search layer. Does it cover other possible scenarios?  Why does a space generate an error? are we maybe neglecting some encoding? a space after or before a word should be an acceptable query string if correctly encoded.

**Comment by nmader** [comment]
@DiegoPino I have updated the pull request title. I think it more accurately reflects what the pull is doing. The search term was already being trimmed twice, once in the function islandora_solr_facet_pages_build_letterer() at: https://github.com/Islandora/islandora_solr_facet_pages/blob/7.x/islandora_solr_facet_pages.module#L162 and again in the function islandora_solr_facet_pages_build_results() here: https://github.com/Islandora/islandora_solr_facet_pages/blob/7.x/islandora_solr_facet_pages.module#L208 . This pull request is just doing the trim earlier to prevent the error.

**Comment by nmader** [comment]
@DiegoPino Just wanted to ping you on this pull request again. From https://jira.duraspace.org/browse/ISLANDORA-1996.

**Comment by DiegoPino** [comment]
@nmader ok, i'm 200% overcommitted but will give it a try again (sorry).

**Comment by nmader** [comment]
@DiegoPino No worries, I just wanted to keep it on everyones radar before I forget about it.

**Comment by DiegoPino** [comment]
Ok, looks harmless. Still not sure why a space breaks search..Since I have not seen any other committer complaining, I will wait for @Islandora/7-x-1-x-committers an extra hour! and then merge. 😄

**Pull request merged**
